services:
  mariadb:
    image: docker.io/library/mariadb:latest
    container_name: coffee-mariadb
    environment:
      MARIADB_DATABASE: coffee
      MARIADB_ROOT_PASSWORD: root1234
    ports:
      - "3306:3306"

  redis:
    image: docker.io/library/redis:latest
    container_name: coffee-redis
    ports:
      - "6379:6379"